### ISSUE TITLE
"run_dsc" runs slow if score function returns a long row vector

### ISSUE THREAD

**Issue by mengyin** [stephens999/dscr#12]
The function "run_dsc" runs very slow when aggregating results if the score function returns a long row vector/list/array (i.e. "results" is a long row vector/list/array).

It might be due to line 140 in "main.R":
return(data.frame(seed=seed, scenario=scenario$name, method=method$name, results))

The "data.frame" function runs slow when combining high dimension row vector, but pretty fast for high dimension column vector. For example, the second command runs much faster than the first command:
> system.time(data.frame(seed=1,t(data.frame(1:10000)),check.names=FALSE))
   user  system elapsed 
  0.035   0.003   0.037 
> system.time(data.frame(seed=1,data.frame(1:10000),check.names=FALSE))
   user  system elapsed 
  0.001   0.000   0.001 

P.S. It is interesting that in this case the "cbind" function runs much faster than "data.frame":
> system.time(cbind(seed=1,t(data.frame(1:10000)),check.names=FALSE))
   user  system elapsed 
  0.001   0.000   0.001

**Comment by stephens999** [comment]
i tried instead using  return(unlist(c(seed=seed, scenario=scenario$name, method=method$name, results))) but that seems to turn all the numbers into strings... (Without unlist ldply complained)

**Comment by jfdegner** [comment]
Here is a way to do it defining a list and then just assigning attributes to this list to make it a data frame.  The speed looks somewhere between cbind and data.frame.   Is there anything wrong with using the cbind option? 

system.time({X<-c(list('SomeText', 200), as.list(1:10000)); class(X) <- 'data.frame'; names(X) <- c('Label', 'Score', paste0('C', 3:length(X))); row.names(X)<-1})
   user  system elapsed 
  0.003   0.000   0.004

**Comment by jfdegner** [comment]
Actually, it seems like most of the time in the above method is in assigning column names.   If you don't care about having those, but are OK with a dataframe without column names, it is as fast as the column vector:

system.time({X<-c(list('SomeText', 200), as.list(1:10000)); class(X) <- 'data.frame'; names(X) <- NULL; row.names(X)<-1})
   user  system elapsed 
  0.001   0.000   0.001

**Comment by stephens999** [comment]
i added a tests/one_sample_location_longoutput directory to test solutions to this

**Comment by stephens999** [comment]
fixed in 9ad330999e47159d94e2c6a2625081bf28b636f6
