### ISSUE TITLE
Function as method output

### ISSUE THREAD

**Issue by jfdegner** [stephens999/dscr#21]
I am working on a dscr and thought it would be best for each method to return a function rather than a value or set of values.   I am running into a problem when the dscr calls get_results_singletrial.   This function attempts to recast the results list as a dataframe, but I don't think this works when one of the elements of the list is a function.  The in progress code is here https://github.com/jfdegner/BlackJack

**Comment by stephens999** [comment]
I think the issue is that score has to output an atomic list, and yours does not.
