### ISSUE TITLE
Vignette depends on ashr

### ISSUE THREAD

**Issue by ramanshah** [stephens999/dscr#32]
The vignette `dsc_shrink.rmd` depends on `ashr`. This causes installation failure for any user who does not previously install `ashr`.

**Comment by stephens999** [comment]
True. Not sure how to resolve this. Is there a standard way?
If we install a package from cran then I guess it automatically installs all
dependencies, but from github that doesn't happen. I guess I could
change the readme to say install_github ashr too....

**Comment by stephens999** [comment]
i modified the readme to include instructions to install ashr

**Comment by ramanshah** [comment]
Thanks!

Also, just to document the dependency tree (given my relatively clean installation), the vignettes want `dplyr` as well.

**Comment by stephens999** [comment]
I have dplyr listed in Imports in the DESCRIPTION file. Do I have to do
something else?

**Comment by ramanshah** [comment]
I'll look into this!

**Comment by ramanshah** [comment]
Ahhh...looks like you imported `plyr` and not `dplyr`.

**Comment by stephens999** [comment]
thx, i updated this

**Comment by stephens999** [comment]
@ramanshah do you think we can close this issue now?

**Comment by stephens999** [comment]
i did find this relevant issue
https://github.com/hadley/devtools/issues/190

**Comment by ramanshah** [comment]
Yep, it does seem tricky. Let's close it; modulo the above, there may be a challenge when it comes time to send it to CRAN, but we'll see.
