### ISSUE TITLE
Warning on load

### ISSUE THREAD

**Issue by ramanshah** [stephens999/dscr#33]
When I load dscr, I get a warning:

```
Warning message:
replacing previous import by ‘psych::%+%’ when loading ‘dscr’ 
```

Not a functional problem, but we'll want to fix it before going public with this package.

**Comment by stephens999** [comment]
we should maybe just avoid psych by implementing winsor ourselves

**Comment by stephens999** [comment]
maybe winsor = function (x, trim = 0.2) 
{
    q <- quantile(x, c(trim, 1 - trim))
    x[x < q[1]] =q[1]
    x[x > q[2]] = q[2]
    return(mean(x))
}

**Comment by ramanshah** [comment]
Agreed; implementing.

**Comment by ramanshah** [comment]
Addressed in https://github.com/stephens999/dscr/pull/39.
