### ISSUE TITLE
Big if-else datamaker in one_sample_location

### ISSUE THREAD

**Issue by ramanshah** [stephens999/dscr#35]
The big set of `if`-`else` blocks in the `one_sample_location` vignette violates the single responsibility principle, and it is encouraging students to write a single, enormous (hundreds of lines) `datamaker` function with similar if-else logic for their own complicated statistical cases. This is digging them in a hole in terms of testing and debugging.

From the codebase it seems that `dscr` allows one to have several simple datamakers that get specified at the `addScenario` level. This seems to me to be better software practice, and we should teach this pattern via the vignette.

(Matthew - I'm filing this issue basically as a todo for myself. Feel free to just wait for me to implement it, unless you disagree or otherwise want to comment.)

**Comment by stephens999** [comment]
I understand your concern. On other hand, this is illustrating the point
that you can have one datamaker that gets reused but with different
parameters....
I realize it isn't the most elegant illustration of that!

would some kind of switch statement satisfy your concern? (does it exist in
R?)

The elegant way to do it would be to pass the generating function itself
(eg rt, rnorm, etc) into the datamaker...

Matthew

**Comment by ramanshah** [comment]
Thinking about this afresh, perhaps passing the generating function itself would be nice - the functional programming tooling to me is one of the nicest things about R and is very lightly used.

**Comment by stephens999** [comment]
that's fine by me.
MS
