### ISSUE TITLE
browseVignette names are not very informative

### ISSUE THREAD

**Issue by stephens999** [stephens999/dscr#37]
when I browseVignettes("dscr") I get
A Vignette to illustrate dscr - HTML  source  R code 
A Vignette to illustrate dscr - HTML  source  R code 

it would be better for the vignettes to have more informative titles!
(and for the elementary vignette to be listed first)

**Comment by ramanshah** [comment]
@stephens999 I know how to fix this (getting the order correct is a fun kind of poetry - vignettes are listed alphabetically), but I'll hold off on a PR until the `prune_psych` is merged. Tons of html output from building the vignettes will turn into merge conflicts.

**Comment by ramanshah** [comment]
Addressed in https://github.com/stephens999/dscr/pull/40.

**Comment by stephens999** [comment]
i merged, but then updated your names a little - I wanted the "simple" example to be clear.
