### ISSUE TITLE
Set up Travis-CI to run automatic build and check

### ISSUE THREAD

**Issue by road2stat** [stephens999/dscr#4]
Another thing appears in my mind is maybe using Travis-CI (https://travis-ci.org) to build and test the package remotely and dynamically - every time we push the commits to GitHub, Travis will rebuild and retest the package. We can run any shell scripts to generate and test the results we want - on their virtual machines. Travis would be useful for team collaboration, and free us from the tedious manual testing.

A short tutorial of Travis-CI:

http://jtleek.com/protocols/travis_bioc_devel/

**Comment by stephens999** [comment]
i'm closing this as it seems to be working!
