### ISSUE TITLE
Confusion with tests/one_sample_location_longoutput

### ISSUE THREAD

**Issue by Lauren-Blake** [stephens999/dscr#50]
In the dscr/tests/one_sample_location_longoutput, there is a non-current version of adding methods and scenarios. It uses the list format instead of the addScenarios and addMethods. I stumbled upon this when writing my dsc and accidentally used this format at first. I think that the presence of this on the general site may be confusing to other first-time users. Thanks!

**Comment by stephens999** [comment]
removed. thx.
