### ISSUE TITLE
install dependencies

### ISSUE THREAD

**Issue by stephens999** [stephens999/dscr#6]
some users are reporting problems with make deps, and particularly installing devtools

**Comment by NKweiwang** [comment]
When I try the "make deps" and there is error says:

* installing *source* package ‘RCurl’ ...
** package ‘RCurl’ successfully unpacked and MD5 sums checked
checking for curl-config... no
Cannot find curl-config
ERROR: configuration failed for package ‘RCurl’
* removing ‘/home/wei/R/x86_64-pc-linux-gnu-library/3.0/RCurl’
ERROR: dependency ‘RCurl’ is not available for package ‘httr’
* removing ‘/home/wei/R/x86_64-pc-linux-gnu-library/3.0/httr’
ERROR: dependencies ‘httr’, ‘RCurl’ are not available for package ‘devtools’
* removing ‘/home/wei/R/x86_64-pc-linux-gnu-library/3.0/devtools’

The downloaded source packages are in
	‘/tmp/Rtmpava4mZ/downloaded_packages’

**Comment by road2stat** [comment]
It seems the `devtools` package depends on the `RCurl` package, and `RCurl` requires `libcurl` to be successfully built, especially under Linux. `RCurl` has binary packages for Mac and Windows, so their  users will not encounter errors when installing `devtools`.

In Ubuntu, installing `libcurl` first would do the tricks for my case:

    sudo apt-get install -y libcurl4-openssl-dev

**Comment by NKweiwang** [comment]
Thank you so much Nan Xiao. It works very well.
