### ISSUE TITLE
problem with single score?

### ISSUE THREAD

**Issue by stephens999** [stephens999/dscr#64]
i have a dsc where I'm outputting the score as a list with one element, score returns
list(diff1=x) say.
The resulting scorename appears to be NA, and this causes a crash.

When I modify the score to return 
list(diff1=x, diff2=0)
everything works ok.

**Comment by ramanshah** [comment]
Where does the crash happen? I see that the way score names get passed around is somewhat irregular, and any traceback data will help me get to the bottom of the issue.

**Comment by stephens999** [comment]
unfortunately (?) I was unable to reproduce this - my dsc runs fine now with a single score... so I'll close for now.
