### ISSUE TITLE
Vignettes Browsing

### ISSUE THREAD

**Issue by xiangzhu** [stephens999/dscr#7]
There are two ways of installing dscr packages: i) devtools::install_github("stephens999/dscr") in R; ii) make in terminal. Only approach (ii) can produce the vignettes in my machine.

Here is the output of approach (i) in Rstudio:
![dscr_vignettes](https://cloud.githubusercontent.com/assets/5986023/5654870/3a1a8774-968d-11e4-9fdd-959db4ab3593.png)

**Comment by xiangzhu** [comment]
Moreover, after I generated the expected vignettes by approach (ii), I tried the approach (i) again. The generated vignettes dissappeared.

**Comment by stephens999** [comment]
Try devtools::install_github("stephens999/dscr",build_vignettes=TRUE)

**Comment by xiangzhu** [comment]
Yes, it is working.

**Comment by stephens999** [comment]
instructions updated

**Comment by stephens999** [comment]
Maybe I should have referenced the commit db23b8e
