### ISSUE TITLE
Reset a scenario

### ISSUE THREAD

**Issue by shtortr** [stephens999/dscr#8]
There is no simple way to delete the output files (data, output, results) from a dsc within R. Add reset functions so that all files can be recreated if dependencies have changed. For example, running reset_scenarios(scenarios) and reset_methods(methods) followed by res=run_dsc(scenarios, methods, score) would run the dsc completely from scratch. Alternatively, a function rerun_dsc(scenarios, methods, score) would do the work of reset followed by run.

**Comment by xiangzhu** [comment]
Josh and Matthew's conversation in the lecture (Jan 12) reminded me an option in `knitr`: `cache`.  Here is the explanation from Yihui Xie (author of `knitr`): 

> when evaluating code chunks, the cached chunks are skipped, but the objects created in these chunks are (lazy-) loaded from previously saved databases (.rdb and .rdx) files, and these files are saved when a chunk is evaluated for the first time, or when cached files are not found (e.g. you may have removed them by hand); 

Yihui also provided some [advanced examples of using `cache`](http://yihui.name/knitr/demo/cache/).

I use `cache=TRUE` when I try to avoid re-running a time-consuming job (e.g. MCMC) from scratch.

I am not sure whether going into details of `cache` will help address this issue.

**Comment by stephens999** [comment]
I implemented two functions reset_method and reset_scenario (only work under unix-alikes at present since use system call to rm...). 222bdc7fe57ab978b6582ed49cd3f6c65c36b1f7

**Comment by stephens999** [comment]
i also started to implement an "overwrite" flag option, but decided to put it on hold....

**Comment by stephens999** [comment]
Jack Degner  pointed out that r has functions like remove. File which would be better to use for cross platform compatibility

**Comment by stephens999** [comment]
now implemented using file.remove; should work across scenarios f0482504d527067fcca2f9e1ab764d147957b5ae

**Comment by stephens999** [comment]
now also implemented method to reset_dsc to do all of them. 4a8b6e3e6ca74541e938fc86d2c7cac536d81844
